// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxX-OJOKpKaYuV6d7liO0vomrwswkLRcA',
    appId: '1:469779211630:web:f5a721f3f0215e07754d7f',
    messagingSenderId: '469779211630',
    projectId: 'hamrodokan-54f97',
    authDomain: 'hamrodokan-54f97.firebaseapp.com',
    storageBucket: 'hamrodokan-54f97.firebasestorage.app',
    measurementId: 'G-DQQSYZSL6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfju9tosxGW2ceK8Tk7t77PUqN3T4JxNQ',
    appId: '1:469779211630:android:43b5919369bbaa66754d7f',
    messagingSenderId: '469779211630',
    projectId: 'hamrodokan-54f97',
    storageBucket: 'hamrodokan-54f97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3eA6kC_qFIdfnwDlXywAStgbI-0jgUNk',
    appId: '1:469779211630:ios:527839b287916f3e754d7f',
    messagingSenderId: '469779211630',
    projectId: 'hamrodokan-54f97',
    storageBucket: 'hamrodokan-54f97.firebasestorage.app',
    androidClientId: '469779211630-h2769g5ptr067pcpogcmi2a5hpsn34b5.apps.googleusercontent.com',
    iosClientId: '469779211630-gf1e1dvou94o58m3rgpguf309jmi5erj.apps.googleusercontent.com',
    iosBundleId: 'com.example.hamrodokan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxX-OJOKpKaYuV6d7liO0vomrwswkLRcA',
    appId: '1:469779211630:web:70547aae3ea3d8a3754d7f',
    messagingSenderId: '469779211630',
    projectId: 'hamrodokan-54f97',
    authDomain: 'hamrodokan-54f97.firebaseapp.com',
    storageBucket: 'hamrodokan-54f97.firebasestorage.app',
    measurementId: 'G-B6FST9CKGV',
  );

}